/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.notificationhubs.v2016_03_01;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.management.notificationhubs.v2016_03_01.implementation.SharedAccessAuthorizationRuleResourceInner;
import com.microsoft.azure.arm.model.Indexable;
import com.microsoft.azure.arm.model.Refreshable;
import com.microsoft.azure.arm.model.Updatable;
import com.microsoft.azure.arm.model.Appliable;
import com.microsoft.azure.arm.model.Creatable;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.notificationhubs.v2016_03_01.implementation.NotificationHubsManager;
import java.util.Map;
import java.util.List;

/**
 * Type representing NamespaceSharedAccessAuthorizationRuleResource.
 */
public interface NamespaceSharedAccessAuthorizationRuleResource extends HasInner<SharedAccessAuthorizationRuleResourceInner>, Indexable, Refreshable<NamespaceSharedAccessAuthorizationRuleResource>, Updatable<NamespaceSharedAccessAuthorizationRuleResource.Update>, HasManager<NotificationHubsManager> {
    /**
     * @return the id value.
     */
    String id();

    /**
     * @return the location value.
     */
    String location();

    /**
     * @return the name value.
     */
    String name();

    /**
     * @return the rights value.
     */
    List<AccessRights> rights();

    /**
     * @return the sku value.
     */
    Sku sku();

    /**
     * @return the tags value.
     */
    Map<String, String> tags();

    /**
     * @return the type value.
     */
    String type();

    /**
     * The entirety of the NamespaceSharedAccessAuthorizationRuleResource definition.
     */
    interface Definition extends DefinitionStages.Blank, DefinitionStages.WithNamespace, DefinitionStages.WithLocation, DefinitionStages.WithProperties, DefinitionStages.WithCreate {
    }

    /**
     * Grouping of NamespaceSharedAccessAuthorizationRuleResource definition stages.
     */
    interface DefinitionStages {
        /**
         * The first stage of a NamespaceSharedAccessAuthorizationRuleResource definition.
         */
        interface Blank extends WithNamespace {
        }

        /**
         * The stage of the namespacesharedaccessauthorizationruleresource definition allowing to specify Namespace.
         */
        interface WithNamespace {
           /**
            * Specifies resourceGroupName, namespaceName.
            */
            WithLocation withExistingNamespace(String resourceGroupName, String namespaceName);
        }

        /**
         * The stage of the namespacesharedaccessauthorizationruleresource definition allowing to specify Location.
         */
        interface WithLocation {
           /**
            * Specifies location.
            */
            WithProperties withLocation(String location);
        }

        /**
         * The stage of the namespacesharedaccessauthorizationruleresource definition allowing to specify Properties.
         */
        interface WithProperties {
           /**
            * Specifies properties.
            */
            WithCreate withProperties(SharedAccessAuthorizationRuleProperties properties);
        }

        /**
         * The stage of the namespacesharedaccessauthorizationruleresource definition allowing to specify Sku.
         */
        interface WithSku {
            /**
             * Specifies sku.
             */
            WithCreate withSku(Sku sku);
        }

        /**
         * The stage of the namespacesharedaccessauthorizationruleresource definition allowing to specify Tags.
         */
        interface WithTags {
            /**
             * Specifies tags.
             */
            WithCreate withTags(Map<String, String> tags);
        }

        /**
         * The stage of the definition which contains all the minimum required inputs for
         * the resource to be created (via {@link WithCreate#create()}), but also allows
         * for any other optional settings to be specified.
         */
        interface WithCreate extends Creatable<NamespaceSharedAccessAuthorizationRuleResource>, DefinitionStages.WithSku, DefinitionStages.WithTags {
        }
    }
    /**
     * The template for a NamespaceSharedAccessAuthorizationRuleResource update operation, containing all the settings that can be modified.
     */
    interface Update extends Appliable<NamespaceSharedAccessAuthorizationRuleResource>, UpdateStages.WithSku, UpdateStages.WithTags {
    }

    /**
     * Grouping of NamespaceSharedAccessAuthorizationRuleResource update stages.
     */
    interface UpdateStages {
        /**
         * The stage of the namespacesharedaccessauthorizationruleresource update allowing to specify Sku.
         */
        interface WithSku {
            /**
             * Specifies sku.
             */
            Update withSku(Sku sku);
        }

        /**
         * The stage of the namespacesharedaccessauthorizationruleresource update allowing to specify Tags.
         */
        interface WithTags {
            /**
             * Specifies tags.
             */
            Update withTags(Map<String, String> tags);
        }

    }
}
