/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.notificationhubs.v2017_04_01;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.arm.resources.models.Resource;
import com.microsoft.azure.arm.resources.models.GroupableResourceCore;
import com.microsoft.azure.arm.resources.models.HasResourceGroup;
import com.microsoft.azure.arm.model.Refreshable;
import com.microsoft.azure.arm.model.Updatable;
import com.microsoft.azure.arm.model.Appliable;
import com.microsoft.azure.arm.model.Creatable;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.notificationhubs.v2017_04_01.implementation.NotificationHubsManager;
import org.joda.time.DateTime;
import com.microsoft.azure.management.notificationhubs.v2017_04_01.implementation.NamespaceResourceInner;

/**
 * Type representing NamespaceResource.
 */
public interface NamespaceResource extends HasInner<NamespaceResourceInner>, Resource, GroupableResourceCore<NotificationHubsManager, NamespaceResourceInner>, HasResourceGroup, Refreshable<NamespaceResource>, Updatable<NamespaceResource.Update>, HasManager<NotificationHubsManager> {
    /**
     * @return the createdAt value.
     */
    DateTime createdAt();

    /**
     * @return the critical value.
     */
    Boolean critical();

    /**
     * @return the dataCenter value.
     */
    String dataCenter();

    /**
     * @return the enabled value.
     */
    Boolean enabled();

    /**
     * @return the metricId value.
     */
    String metricId();

    /**
     * @return the namespaceResourceName value.
     */
    String namespaceResourceName();

    /**
     * @return the namespaceType value.
     */
    NamespaceType namespaceType();

    /**
     * @return the provisioningState value.
     */
    String provisioningState();

    /**
     * @return the region value.
     */
    String region();

    /**
     * @return the scaleUnit value.
     */
    String scaleUnit();

    /**
     * @return the serviceBusEndpoint value.
     */
    String serviceBusEndpoint();

    /**
     * @return the sku value.
     */
    Sku sku();

    /**
     * @return the status value.
     */
    String status();

    /**
     * @return the subscriptionId value.
     */
    String subscriptionId();

    /**
     * @return the updatedAt value.
     */
    DateTime updatedAt();

    /**
     * The entirety of the NamespaceResource definition.
     */
    interface Definition extends DefinitionStages.Blank, DefinitionStages.WithGroup, DefinitionStages.WithCreate {
    }

    /**
     * Grouping of NamespaceResource definition stages.
     */
    interface DefinitionStages {
        /**
         * The first stage of a NamespaceResource definition.
         */
        interface Blank extends GroupableResourceCore.DefinitionWithRegion<WithGroup> {
        }

        /**
         * The stage of the NamespaceResource definition allowing to specify the resource group.
         */
        interface WithGroup extends GroupableResourceCore.DefinitionStages.WithGroup<WithCreate> {
        }

        /**
         * The stage of the namespaceresource update allowing to specify CreatedAt.
         */
        interface WithCreatedAt {
            /**
             * Specifies createdAt.
             */
            WithCreate withCreatedAt(DateTime createdAt);
        }

        /**
         * The stage of the namespaceresource update allowing to specify Critical.
         */
        interface WithCritical {
            /**
             * Specifies critical.
             */
            WithCreate withCritical(Boolean critical);
        }

        /**
         * The stage of the namespaceresource update allowing to specify DataCenter.
         */
        interface WithDataCenter {
            /**
             * Specifies dataCenter.
             */
            WithCreate withDataCenter(String dataCenter);
        }

        /**
         * The stage of the namespaceresource update allowing to specify Enabled.
         */
        interface WithEnabled {
            /**
             * Specifies enabled.
             */
            WithCreate withEnabled(Boolean enabled);
        }

        /**
         * The stage of the namespaceresource update allowing to specify NamespaceCreateOrUpdateParametersName.
         */
        interface WithNamespaceCreateOrUpdateParametersName {
            /**
             * Specifies namespaceCreateOrUpdateParametersName.
             */
            WithCreate withNamespaceCreateOrUpdateParametersName(String namespaceCreateOrUpdateParametersName);
        }

        /**
         * The stage of the namespaceresource update allowing to specify NamespaceType.
         */
        interface WithNamespaceType {
            /**
             * Specifies namespaceType.
             */
            WithCreate withNamespaceType(NamespaceType namespaceType);
        }

        /**
         * The stage of the namespaceresource update allowing to specify ProvisioningState.
         */
        interface WithProvisioningState {
            /**
             * Specifies provisioningState.
             */
            WithCreate withProvisioningState(String provisioningState);
        }

        /**
         * The stage of the namespaceresource update allowing to specify Region.
         */
        interface WithRegion {
            /**
             * Specifies region.
             */
            WithCreate withRegion(String region);
        }

        /**
         * The stage of the namespaceresource update allowing to specify ScaleUnit.
         */
        interface WithScaleUnit {
            /**
             * Specifies scaleUnit.
             */
            WithCreate withScaleUnit(String scaleUnit);
        }

        /**
         * The stage of the namespaceresource update allowing to specify ServiceBusEndpoint.
         */
        interface WithServiceBusEndpoint {
            /**
             * Specifies serviceBusEndpoint.
             */
            WithCreate withServiceBusEndpoint(String serviceBusEndpoint);
        }

        /**
         * The stage of the namespaceresource update allowing to specify Sku.
         */
        interface WithSku {
            /**
             * Specifies sku.
             */
            WithCreate withSku(Sku sku);
        }

        /**
         * The stage of the namespaceresource update allowing to specify Status.
         */
        interface WithStatus {
            /**
             * Specifies status.
             */
            WithCreate withStatus(String status);
        }

        /**
         * The stage of the namespaceresource update allowing to specify SubscriptionId.
         */
        interface WithSubscriptionId {
            /**
             * Specifies subscriptionId.
             */
            WithCreate withSubscriptionId(String subscriptionId);
        }

        /**
         * The stage of the namespaceresource update allowing to specify UpdatedAt.
         */
        interface WithUpdatedAt {
            /**
             * Specifies updatedAt.
             */
            WithCreate withUpdatedAt(DateTime updatedAt);
        }

        /**
         * The stage of the definition which contains all the minimum required inputs for
         * the resource to be created (via {@link WithCreate#create()}), but also allows
         * for any other optional settings to be specified.
         */
        interface WithCreate extends Creatable<NamespaceResource>, Resource.DefinitionWithTags<WithCreate>, DefinitionStages.WithCreatedAt, DefinitionStages.WithCritical, DefinitionStages.WithDataCenter, DefinitionStages.WithEnabled, DefinitionStages.WithNamespaceCreateOrUpdateParametersName, DefinitionStages.WithNamespaceType, DefinitionStages.WithProvisioningState, DefinitionStages.WithRegion, DefinitionStages.WithScaleUnit, DefinitionStages.WithServiceBusEndpoint, DefinitionStages.WithSku, DefinitionStages.WithStatus, DefinitionStages.WithSubscriptionId, DefinitionStages.WithUpdatedAt {
        }
    }
    /**
     * The template for a NamespaceResource update operation, containing all the settings that can be modified.
     */
    interface Update extends Appliable<NamespaceResource>, Resource.UpdateWithTags<Update>, UpdateStages.WithSku {
    }

    /**
     * Grouping of NamespaceResource update stages.
     */
    interface UpdateStages {
        /**
         * The stage of the namespaceresource {0} allowing to specify Sku.
         */
        interface WithSku {
            /**
             * Specifies sku.
             */
            Update withSku(Sku sku);
        }

    }
}
