/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.databox;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Copy progress.
 */
public class CopyProgress {
    /**
     * Name of the storage account where the data needs to be uploaded.
     */
    @JsonProperty(value = "storageAccountName", access = JsonProperty.Access.WRITE_ONLY)
    private String storageAccountName;

    /**
     * Id of the account where the data needs to be uploaded.
     */
    @JsonProperty(value = "accountId", access = JsonProperty.Access.WRITE_ONLY)
    private String accountId;

    /**
     * Amount of data uploaded by the job as of now.
     */
    @JsonProperty(value = "bytesSentToCloud", access = JsonProperty.Access.WRITE_ONLY)
    private Long bytesSentToCloud;

    /**
     * Total amount of data to be processed by the job.
     */
    @JsonProperty(value = "totalBytesToProcess", access = JsonProperty.Access.WRITE_ONLY)
    private Long totalBytesToProcess;

    /**
     * Get name of the storage account where the data needs to be uploaded.
     *
     * @return the storageAccountName value
     */
    public String storageAccountName() {
        return this.storageAccountName;
    }

    /**
     * Get id of the account where the data needs to be uploaded.
     *
     * @return the accountId value
     */
    public String accountId() {
        return this.accountId;
    }

    /**
     * Get amount of data uploaded by the job as of now.
     *
     * @return the bytesSentToCloud value
     */
    public Long bytesSentToCloud() {
        return this.bytesSentToCloud;
    }

    /**
     * Get total amount of data to be processed by the job.
     *
     * @return the totalBytesToProcess value
     */
    public Long totalBytesToProcess() {
        return this.totalBytesToProcess;
    }

}
