/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.databox;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Details for the destination account.
 */
public class DestinationAccountDetails {
    /**
     * Destination storage account id.
     */
    @JsonProperty(value = "accountId", required = true)
    private String accountId;

    /**
     * Get destination storage account id.
     *
     * @return the accountId value
     */
    public String accountId() {
        return this.accountId;
    }

    /**
     * Set destination storage account id.
     *
     * @param accountId the accountId value to set
     * @return the DestinationAccountDetails object itself.
     */
    public DestinationAccountDetails withAccountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

}
